services:
  frontend:
    build: ./frontend
    container_name: frontend_c
    environment:
      - VITE_APP_API_URL=$DOCKER_VITE_APP_API_URL
    ports:
      - "8080:8080"
  backend:
    build: ./backend
    container_name: backend_c
    environment:
      - MONGODB_URI=$DOCKER_MONGODB_URI
    ports:
      - "4000:4000"
    stdin_open: true
    tty: true
